

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: /home/deepuser/tdamet/yolov56d/data/blue/train.txt 
val: /home/deepuser/tdamet/yolov56d/data/blue/test.txt 
test: /home/deepuser/tdamet/yolov56d/data/blue/test.txt 

mesh: /home/deepuser/tdamet/yolov56d/data/blue/blue.ply
tr_range: /home/deepuser/tdamet/yolov56d/data/blue/training_range.txt
backup : /home/deepuser/tdamet/yolov56d/backup/blue
names : ["blue"]

#background_path: "/home/deepuser/tdamet/yolov56d/data/VOCdevkit/VOC2012/JPEGImages"
coords: 18

diam : 0.4
gpus : 0

nc: 1  # number of classes

fx: 570.2067
fy: 571.7008
u0: 320.0
v0: 240.0
