

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ../data/Dataset/box/train.txt
val: ../data/Dataset/box/test.txt
test: ../data/Dataset/box/test.txt

mesh: ../data/Dataset/box/aligned_box_yolo.ply
tr_range: ../data/Dataset/box/training_range.txt
backup : ../backup/box
names : ["box"]

background_path: "../data/VOCdevkit/VOC2012/JPEGImages"
coords: 18

diam : 0.6
gpus : 0

nc: 1  # number of classes

fx: 457.142853
fy: 615.384644
u0: 320.0
v0: 240.0