

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ../data/Dataset/chair/train.txt
val: ../data/Dataset/chair/test.txt
test: ../data/Dataset/chair/test.txt

mesh: ../data/Dataset/chair/sit_stand_chair_aligned.ply
tr_range: ../data/Dataset/chair/training_range.txt
backup : ../backup/chair
names : ["chair"]

background_path: "../data/VOCdevkit/VOC2012/JPEGImages"
coords: 18

diam : 1.05
gpus : 0

nc: 1  # number of classes

fx: 570.2067
fy: 571.7008
u0: 320.0
v0: 240.0