

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ../data/Dataset/os/train.txt
val: ../data/Dataset/os/test.txt
test: ../data/Dataset/os/test.txt

mesh: ../data/Dataset/os/os.ply
tr_range: ../data/Dataset/os/training_range.txt
backup : ../backup/os
names : ["os"]

background_path: "../data/VOCdevkit/VOC2012/JPEGImages"
coords: 18

diam : 0.3
gpus : 0

nc: 1  # number of classes

fx: 570.2067
fy: 571.7008
u0: 320.0
v0: 240.0